version: '3'

services:
  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hospital

  eureka-server:
    image: akshaynile8849/eureka-server
    ports: 
      - 8761:8761
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

  gateway-microservice:
    image: akshaynile8849/gateway-microservice
    restart: always
    depends_on:
      - eureka-server
    ports:
      - 8080:8080
      
  authentication-microservice:
    image: akshaynile8849/authentication-microservice
    restart: always
    depends_on:
      - eureka-server
    ports:
      - 8088:8088

  procedure-microservice:
    image: akshaynile8849/procedure-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8089:8089

  medication-microservice:
    image: akshaynile8849/medication-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8087:8087

  diagnosis-microservice:
    image: akshaynile8849/diagnosis-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8086:8086

  allergy-microservice:
    image: akshaynile8849/allergy-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8090:8090

  notes-microservice:
    image: akshaynile8849/notes-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8084:8084

  hospital-microservice:
    image: akshaynile8849/hospital-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8082:8082

  patient-visits-microservice:
    image: akshaynile8849/patient-visits-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8085:8085

  appointment-microservice:
    image: akshaynile8849/appointment-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8083:8083

  admin-microservice:
    image: akshaynile8849/admin-microservice
    restart: always
    depends_on:
      - postgres-db
      - eureka-server
    ports:
      - 8081:8081
