server:
  port: 8080
  
spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: authentication-microservice
        uri: http://authentication-microservice:8088
        predicates:
        - Path=/authenticate/**
        
      - id: admin-microservice
        uri: http://admin-microservice:8081
        predicates:
        - Path=/admin/**
        
      - id: hospital-microservice
        uri: http://hospital-microservice:8082
        predicates:
        - Path=/hospital/**
        
      - id: appointment-microservice
        uri: http://appointment-microservice:8083
        predicates:
        - Path=/appointments/**
        
      - id: notes-microservice
        uri: http://notes-microservice:8084
        predicates:
        - Path=/notes/**
        
      - id: patient-visits-microservice
        uri: http://patient-visits-microservice:8085
        predicates:
        - Path=/patient-visits/**
        
      - id: diagnosis-microservice
        uri: http://diagnosis-microservice:8086
        predicates:
        - Path=/diagnosis/**
        
      - id: medication-microservice
        uri: http://medication-microservice:8087
        predicates:
        - Path=/medications/**
        
      - id: procedure-microservice
        uri: http://procedure-microservice:8089
        predicates:
        - Path=/procedures/**
        
      - id: allergy-microservice
        uri: http://allergy-microservice:8090
        predicates:
        - Path=/allergy/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

