server:
  port: 8080
  
spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      routes:
      - id: admin-microservice
        uri: http://localhost:8081
        predicates:
        - Path=/admin/**
      - id: hospital-microservice
        uri: http://localhost:8082
        predicates:
        - Path=/hospital/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost