server:
  port: 8080
  
spring:
  application:
    name: gateway-microservice
  cloud:
    gateway:
      default-filters:      - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: authentication-microservice
        uri: http://localhost:8088
        predicates:
        - Path=/authenticate/**
      - id: admin-microservice
        uri: http://localhost:8081
        predicates:
        - Path=/admin/**
      - id: hospital-microservice
        uri: http://localhost:8082
        predicates:
        - Path=/hospital/**
      - id: appointment-microservice
        uri: http://localhost:8083
        predicates:
        - Path=/appointments/**
      - id: notes-microservice
        uri: http://localhost:8084
        predicates:
        - Path=/notes/**
      - id: patient-visits-microservice
        uri: http://localhost:8085
        predicates:
        - Path=/patient-visits/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
